import "./globals.css"
import type { Metadata } from "next"
import { Inter as FontSans, Outfit } from "next/font/google"
import { cn } from "@/lib/utils"
import ThemeProvider from "@/components/theme-provider"
import Script from "next/script"

const fontSans = Outfit({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("min-h-screen font-sans antialiased", fontSans.variable)}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
        <Script
          type="text/javascript"
          src="https://platform-api.sharethis.com/js/sharethis.js#property=651ea0ee6ee9de001217ae58&product=inline-share-buttons"
          async
        ></Script>
      </body>
    </html>
  )
}
